[workspace]
members = [
    "crates/dbtective-cli",
    "crates/dbtective-core",
]


[workspace.dependencies]
anyhow = "1.0.98"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
walkdir = "2.0"