[package]
name = "dbtective-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
dbtective-core = { path = "../dbtective-core" }